# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basicim_nugget.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basicim_nugget.proto',
  package='cosc435',
  syntax='proto2',
  serialized_pb=_b('\n\x14\x62\x61sicim_nugget.proto\x12\x07\x63osc435\"U\n\rBasicIMNugget\x12\x10\n\x08nickname\x18\x01 \x02(\x0c\x12\x12\n\nen_message\x18\x02 \x02(\x0c\x12\x12\n\nau_message\x18\x03 \x02(\t\x12\n\n\x02iv\x18\x04 \x02(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BASICIMNUGGET = _descriptor.Descriptor(
  name='BasicIMNugget',
  full_name='cosc435.BasicIMNugget',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nickname', full_name='cosc435.BasicIMNugget.nickname', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='en_message', full_name='cosc435.BasicIMNugget.en_message', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='au_message', full_name='cosc435.BasicIMNugget.au_message', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iv', full_name='cosc435.BasicIMNugget.iv', index=3,
      number=4, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=118,
)

DESCRIPTOR.message_types_by_name['BasicIMNugget'] = _BASICIMNUGGET

BasicIMNugget = _reflection.GeneratedProtocolMessageType('BasicIMNugget', (_message.Message,), dict(
  DESCRIPTOR = _BASICIMNUGGET,
  __module__ = 'basicim_nugget_pb2'
  # @@protoc_insertion_point(class_scope:cosc435.BasicIMNugget)
  ))
_sym_db.RegisterMessage(BasicIMNugget)


# @@protoc_insertion_point(module_scope)
